name: Build Windows

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Windows SDK
      uses: GuillaumeFalourd/setup-windows10-sdk-action@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      if: false
      run: npm install

    - name: Find Windows Kit Path
      run: |
        $windowsKitPath = (Get-ChildItem "C:\Program Files (x86)\Windows Kits\10\bin" -Recurse -File -Filter "makeappx.exe" | Select-Object -First 1).DirectoryName
        echo "WINDOWS_KIT_PATH=$windowsKitPath" >> $GITHUB_ENV
      shell: pwsh

    - name: Print Windows Kit Path
      run: |
        echo "Windows Kit Path: $windowsKitPath"
      shell: pwsh
