name: Build and Test Electron App

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main
      - feature/*

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: ['20.x']
        architecture: [x64, arm64]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Set environment variables for platform and architecture (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          echo "ARCHITECTURE=${{ matrix.architecture }}" >> $GITHUB_ENV
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            echo "PLATFORM=linux" >> $GITHUB_ENV
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            echo "PLATFORM=darwin" >> $GITHUB_ENV
        shell: bash

      - name: Set environment variables for platform and architecture (Windows)
        if: runner.os == 'Windows'
        run: |
          echo "ARCHITECTURE=${{ matrix.architecture }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "PLATFORM=win32" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        shell: powershell

      - name: Build app with platform and architecture
        run: npm run make -- --platform=$PLATFORM --arch=$ARCHITECTURE

      - name: Verify build output
        run: ls out/make
