name: Build Windows

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Microsoft Build Tools
      run: |
        choco install microsoft-build-tools -y
      shell: pwsh

    - name: Verify makeappx.exe
      run: |
        $makeappxPath = 'C:\Program Files (x86)\Windows Kits\10\App Certification Kit\makeappx.exe'
        if (Test-Path $makeappxPath) {
            echo "makeappx.exe found at $makeappxPath"
            echo "WINDOWS_KIT_PATH=C:\Program Files (x86)\Windows Kits\10\App Certification Kit" >> $env:GITHUB_ENV
        } else {
            Write-Error "makeappx.exe not found."
            exit 1
        }
      shell: pwsh

    - name: Generate Dev Certificate
      run: |
        $certPassword = [guid]::NewGuid().ToString()
        $certPath = "$(Get-Location)\devcert.pfx"
        $cert = New-SelfSignedCertificate -DnsName "CN=DevCert" -CertStoreLocation "Cert:\CurrentUser\My" -NotAfter (Get-Date).AddYears(1)
        Export-PfxCertificate -Cert $cert -FilePath $certPath -Password (ConvertTo-SecureString -String $certPassword -Force -AsPlainText)
        echo "CERT_PATH=$certPath" >> "$GITHUB_ENV"
        echo "CERT_PASSWORD=$certPassword" >> "$GITHUB_ENV"
        echo "Generated CERT_PATH: $certPath"
        echo "Generated CERT_PASSWORD: $certPassword"
      shell: pwsh

    - name: Verify CERT_PATH and CERT_PASSWORD
      run: |
        if (-not $env:CERT_PATH) {
            Write-Error "CERT_PATH is not set."
            exit 1
        }
        if (-not $env:CERT_PASSWORD) {
            Write-Error "CERT_PASSWORD is not set."
            exit 1
        }
        echo "CERT_PATH is set to $env:CERT_PATH"
        echo "CERT_PASSWORD is set to $env:CERT_PASSWORD"
      shell: pwsh

    - name: Print Windows Kit Path
      run: |
        echo "Windows Kit Path: $env:WINDOWS_KIT_PATH"
      shell: pwsh

    - name: Install dependencies
      run: npm install

    - name: Build app
      run: npm run make
      env:
        WINDOWS_KIT_PATH: ${{ env.WINDOWS_KIT_PATH }}
        CERT_PATH: ${{ env.CERT_PATH }}
        CERT_PASSWORD: ${{ env.CERT_PASSWORD }}
