name: Build Windows

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Microsoft Build Tools
      run: |
        choco install microsoft-build-tools -y
      shell: pwsh

    - name: Install dependencies
      run: npm install

    - name: Build app
      run: npm run make
      env:
        WINDOWS_KIT_PATH: ${{ env.WINDOWS_KIT_PATH }}
      shell: pwsh

    - name: Extract version from package.json
      run: |
        $version = (node -e "console.log(require('./package.json').version);")
        echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      shell: pwsh

    - name: Upload files to Cloudflare R2
      run: |
        $files = Get-ChildItem -Path out\make\ -File
        foreach ($file in $files) {
          Write-Host "Uploading $($file.Name)"
          aws s3 cp $file.FullName "s3://${{ secrets.R2_BUCKET }}/releases/v${{ env.VERSION }}/$($file.Name)" `
            --endpoint-url="${{ secrets.R2_ENDPOINT }}" --debug
        }
      shell: pwsh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.R2_REGION }}
