name: Build Windows

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Windows SDK
      run: choco install windows-sdk-10-version-2004-all -y
      shell: pwsh

    - name: Get Windows Kit Path
      run: |
        $windowsKitPath = (Get-ItemProperty 'HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows Kits\Installed Roots').'KitsRoot10'
        echo "Windows Kit Path: ${windowsKitPath}bin\x64"
        echo "WINDOWS_KIT_PATH=${windowsKitPath}bin\x64" >> $GITHUB_ENV
      shell: pwsh

