name: Build Windows

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Visual Studio Build Tools with Windows SDK
      run: |
        curl -LO https://aka.ms/vs/17/release/vs_buildtools.exe
        .\vs_buildtools.exe --add Microsoft.VisualStudio.Component.Windows10SDK.19041 --quiet --wait --norestart
      shell: cmd

    - name: Verify makeappx.exe
      run: |
        $makeappxPath = Get-Command -CommandType Application -Name makeappx.exe | Select-Object -First 1 -ExpandProperty Definition
        if ($makeappxPath) {
            echo "makeappx.exe found at $makeappxPath"
            $directory = [System.IO.Path]::GetDirectoryName($makeappxPath)
            echo "WINDOWS_KIT_PATH=$directory" >> $env:GITHUB_ENV
        } else {
            Write-Error "makeappx.exe not found."
            exit 1
        }
      shell: pwsh


    - name: Print Windows Kit Path
      run: |
        echo "Windows Kit Path: $env:WINDOWS_KIT_PATH"
      shell: pwsh

    - name: Install dependencies
      run: npm install

    - name: Build app
      run: npm run make
      env:
        WINDOWS_KIT_PATH: ${{ env.WINDOWS_KIT_PATH }}
