name: Build Windows

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Windows SDK
      run: |
        choco install visualstudio-installer -y
        vs_installer.exe install --installPath "C:\BuildTools" --add Microsoft.VisualStudio.Component.Windows10SDK.19041 --quiet --wait
      shell: cmd

    - name: Get Windows Kit Path and Verify makeappx.exe
      run: |
        $windowsKitPath = (Get-ItemProperty 'HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows Kits\Installed Roots').'KitsRoot10'
        $makeappxPath = Join-Path -Path $windowsKitPath -ChildPath 'bin\x64\makeappx.exe'
        if (Test-Path $makeappxPath) {
            echo "Windows Kit Path: $windowsKitPath"
            echo "makeappx.exe found at $makeappxPath"
            echo "WINDOWS_KIT_PATH=${windowsKitPath}bin\x64" >> $GITHUB_ENV
        } else {
            Write-Error "makeappx.exe not found in Windows Kit Path."
            exit 1
        }
      shell: pwsh

    - name: Print Windows Kit Path
      run: echo "Windows Kit Path: $env:WINDOWS_KIT_PATH"
      shell: pwsh

    - name: Install dependencies
      run: npm install

    - name: Build app
      run: npm run make
      env:
        WINDOWS_KIT_PATH: ${{ env.WINDOWS_KIT_PATH }}
