name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build and Package the app
        run: npm run package

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: comet-${{ matrix.os }}
          path: out/make/**/*.*

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: comet-${{ matrix.os }}
          path: ./artifacts/${{ matrix.os }}

      - name: Publish to GitHub Releases
        run: npm run publish -- --prerelease
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
