name: Release

on:
  push:
    branches:
      - release

jobs:
  build-and-publish:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        arch: [x64, arm64]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Electron app
        run: |
          npm run make -- --arch=${{ matrix.arch }}
        env:
          ELECTRON_CACHE: ${{ runner.temp }}/electron
          npm_config_arch: ${{ matrix.arch }}
          npm_config_platform: ${{ matrix.os }}

      - name: Extract version from package.json
        id: version
        run: |
          node -e "const fs = require('fs'); const version = JSON.parse(fs.readFileSync('package.json')).version; console.log(`VERSION=${version}`);" >> $GITHUB_ENV
        shell: bash

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: all-distributables

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.R2_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.R2_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1

      - name: Upload each file to Cloudflare R2
        run: |
          echo "R2_BUCKET: ${{ secrets.R2_BUCKET }}"
          echo "R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}"
          for file in $(find out/make/ -type f); do
            filename=$(basename $file)
            echo "Uploading $filename"
            aws s3 cp "$file" "s3://${{ secrets.R2_BUCKET }}/releases/v${{ env.VERSION }}/$filename" \
              --endpoint-url="${{ secrets.R2_ENDPOINT }}" \
              --acl public-read
          done
