name: Release

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [macos-latest]
        arch: [x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Electron app
        run: |
          npm run make -- --arch=${{ matrix.arch }}
        env:
          ELECTRON_CACHE: ${{ runner.temp }}/electron
          npm_config_arch: ${{ matrix.arch }}
          npm_config_platform: ${{ matrix.os }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}-distributables
          path: out/make

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Extract version from package.json
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: all-distributables

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.R2_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.R2_SECRET_ACCESS_KEY }}
          aws configure set default.region weur

      - name: Upload each file to Cloudflare R2
        run: |
          echo "R2_BUCKET: ${{ secrets.R2_BUCKET }}"
          echo "R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}"
          for file in $(find all-distributables/ -type f); do
            filename=$(basename $file)
            echo "Uploading $filename"
            aws s3 cp $file s3://${{ secrets.R2_BUCKET }}/releases/v${{ env.VERSION }}/$filename \
              --endpoint-url=${{ secrets.R2_ENDPOINT }} \
              --acl public-read
          done
