name: Release

on:
  push:
    branches:
      - release

jobs:
  build-and-publish:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        arch: [x64, arm64]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Electron app
        run: |
          npm run make -- --arch=${{ matrix.arch }}
        env:
          ELECTRON_CACHE: ${{ runner.temp }}/electron
          npm_config_arch: ${{ matrix.arch }}
          npm_config_platform: ${{ matrix.os }}

      - name: Extract version from package.json
        id: version
        run: |
          node -e "const fs = require('fs'); const version = JSON.parse(fs.readFileSync('package.json')).version; console.log(`VERSION=${version}`);" >> $GITHUB_ENV
        shell: bash

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: all-distributables

      - name: Upload files to Cloudflare R2
        run: |
          for file in $(find out/make/ -type f); do
            filename=$(basename $file)
            echo "Uploading $filename"
            gh workflow run magicwallet/r2-upload@main \
              -f endpoint=${{ secrets.R2_ENDPOINT }} \
              -f access_key_id=${{ secrets.R2_ACCESS_KEY_ID }} \
              -f secret_access_key=${{ secrets.R2_ACCESS_SECRET_KEY }} \
              -f bucket=${{ secrets.R2_BUCKET }} \
              -f file=$file \
              -f destination="/releases/v${{ env.VERSION }}/$filename"
          done
        shell: bash
        env:
         GH_TOKEN: ${{ secrets.GH_TOKEN }}
